### ISSUE TITLE
📝 (releases) `deps-dev` coming back as `analytics`

### ISSUE THREAD

**Issue by JeromeFitz** [JeromeFitz/packages#744]
Something goofy going on with the particular selection of:

#### 📦 Add or update compiled files or packages

Always coming back as:

#### 📈 Add or update analytics or track code

This is probably a good point to determine if it is because of the index selection on the emoji find, or if this in general could be greatly reduced in complexity by moving back to a `json` file (that can be dynamically generated) instead of a  dynamically created object of information. Instead of trying to finagle a way to add to `release.config.cjs` or other configuration files, may be ideal to just allow for a `json` file swap with some examples. I think it would make things much smaller in general.

Could also help with a potential adoption if we can use this is a jumping point RE: #729

**Comment by ygorluiz** [comment]
@JeromeFitz I think you would like to know this lib [vanilla-extract](https://github.com/vanilla-extract-css/vanilla-extract) 
I think stitches is almost dying or even already died 🔥

**Comment by JeromeFitz** [comment]
🤔  Even weirder, it is only when `renovate` is the author of the commit:
- https://github.com/JeromeFitz/packages/releases/tag/%40jeromefitz%2Fspotify%402.3.3

Thanks for sharing about `vanilla-extract` @ygorluiz 

With Next 13, re-looking at how they prefer styling to take place. May make the move depending on how the next few weeks play out with them. As right now using `stitches` (or `vanilla`) you cannot migrate to the `./app` system away from `./pages`

**Comment by ygorluiz** [comment]
get ready [Next.js 13 upgrade guide](https://twitter.com/shadcn/status/1584971527820541953)

**Comment by JeromeFitz** [comment]
🎉  Exciting times indeed.

This is the call-out about `stitches` to be aware of currently:
- https://beta.nextjs.org/docs/styling/css-in-js

**Comment by JeromeFitz** [comment]
More than likely going to move back to `tailwind` w/ `radix-ui` sometime over the next few months for the `design-system` to take advantaged of Next 13 fully.

The original intent of this issue is going to be looked at again soon-ish with the  release of 🎉 [`ccommit`](https://github.com/JeromeFitz/packages/tree/main/packages/ccommit) 
- Probably in Q1

**Comment by ygorluiz** [comment]
I don't know if it's fully working but apparently the basics are ok
https://nextplate-13.vercel.app/styling/stitches
https://github.com/ygorluiz/nextplate-13/tree/main/app/styling/stitches
